// Generated by Locust setup. Native contract pinned to Pi 2db5e359bf84c1c0be51d2c5c5c5c7cf27072c2b.
import { spawn } from "node:child_process";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

const launcher = __LOCUST_LAUNCHER_JSON__;
const hookTimeoutMs = __LOCUST_HOOK_TIMEOUT_MS__;
const failureLine = __LOCUST_FAILURE_LINE_JSON__;

type HookOutput = { line: string | null; keep_going: boolean };
type NativeEvent = Record<string, any>;

function output(text: string, event: string): HookOutput | undefined {
    if (text.trim() === "") return undefined;
    const value = JSON.parse(text);
    if (value === null || typeof value !== "object" || Array.isArray(value)
        || Object.keys(value).some((key) => key !== "line" && key !== "keep_going")
        || typeof value.keep_going !== "boolean"
        || (value.line !== null && (typeof value.line !== "string"
            || value.line.length === 0 || value.line.length >= 512
            || !/^[\x20-\x7e]+$/.test(value.line)))
        || (value.keep_going && (event !== "stop" || value.line === null))) {
        throw new Error("Invalid hook output");
    }
    return value.line === null ? undefined : value;
}

function payload(event: NativeEvent, sessionId: string): Record<string, unknown> {
    const value: Record<string, unknown> = {
        session_id: sessionId,
        hook_event_name: event.type,
    };
    if (event.type === "session_compact") value.source = "compact";
    else if (event.type === "session_start") value.source = event.reason;
    if (event.type === "tool_result") {
        value.tool_name = event.toolName;
        value.tool_use_id = event.toolCallId;
        value.tool_input = event.input;
        if (event.parentToolCallId !== undefined) value.parent_tool_call_id = event.parentToolCallId;
        value.tool_response = {
            isError: event.isError,
            details: { server: event.details?.server, tool: event.details?.tool },
            structuredContent: event.structuredContent,
        };
    }
    return value;
}

export default function locust(pi: ExtensionAPI): void {
    let epoch = 0;
    let closed = false;
    const active = new Map<() => void, Promise<void>>();

    function valid(ctx: ExtensionContext, sessionId: string, generation: number): boolean {
        try {
            return !closed && generation === epoch && !ctx.signal?.aborted
                && ctx.sessionManager.getSessionId() === sessionId;
        } catch {
            return false;
        }
    }

    async function run(event: NativeEvent, kind: string, ctx: ExtensionContext): Promise<HookOutput | undefined> {
        if (process.env.LOCUST_HOOKS === "off" || closed) return undefined;
        const generation = epoch;
        let sessionId: string;
        let signal: AbortSignal | undefined;
        let input: string;
        try {
            sessionId = ctx.sessionManager.getSessionId();
            signal = ctx.signal;
            if (typeof sessionId !== "string" || sessionId === "" || signal?.aborted) return undefined;
            input = JSON.stringify(payload(event, sessionId));
        } catch {
            return { line: failureLine, keep_going: false };
        }
        const result = await new Promise<HookOutput | undefined>((resolve) => {
            let child: ReturnType<typeof spawn>;
            let timer: ReturnType<typeof setTimeout> | undefined;
            let text = "";
            let done = false;
            let cancelled = false;
            let fault = false;
            let closeFinished!: () => void;
            const closedPromise = new Promise<void>((closedResolve) => { closeFinished = closedResolve; });
            function finish(value: HookOutput | undefined): void {
                if (done) return;
                done = true;
                clearTimeout(timer);
                signal?.removeEventListener("abort", cancel);
                active.delete(cancel);
                closeFinished();
                resolve(value);
            }
            function kill(): void {
                if (child?.exitCode === null && child?.signalCode === null) {
                    try { child.kill("SIGKILL"); } catch { /* already gone */ }
                }
            }
            function cancel(): void {
                if (done) return;
                cancelled = true;
                clearTimeout(timer);
                kill();
                if (child?.pid === undefined) finish(undefined);
            }
            function failed(): void {
                if (done) return;
                fault = true;
                clearTimeout(timer);
                kill();
                if (child?.pid === undefined) finish({ line: failureLine, keep_going: false });
            }
            try {
                child = spawn(launcher, ["hook", kind, "--harness", "pi"], {
                    shell: false,
                    stdio: ["pipe", "pipe", "ignore"],
                });
            } catch {
                finish({ line: failureLine, keep_going: false });
                return;
            }
            active.set(cancel, closedPromise);
            signal?.addEventListener("abort", cancel, { once: true });
            timer = setTimeout(failed, hookTimeoutMs);
            child.stdout?.setEncoding("utf8");
            child.stdout?.on("data", (chunk: string) => { if (!done) text += chunk; });
            child.on("error", () => {
                if (cancelled) finish(undefined);
                else failed();
            });
            child.on("close", (code) => {
                if (done) return;
                if (cancelled) { finish(undefined); return; }
                if (fault || code !== 0) { finish({ line: failureLine, keep_going: false }); return; }
                try { finish(output(text, kind)); }
                catch { finish({ line: failureLine, keep_going: false }); }
            });
            child.stdin?.on("error", failed);
            if (signal?.aborted) cancel();
            else child.stdin?.end(input);
        });
        return valid(ctx, sessionId, generation) ? result : undefined;
    }

    async function start(event: NativeEvent, ctx: ExtensionContext): Promise<void> {
        const value = await run(event, "start", ctx);
        if (value?.line) pi.sendMessage({ customType: "locust", content: value.line, display: true }, { triggerTurn: false });
    }

    pi.on("session_start", async (event, ctx) => {
        closed = false;
        epoch++;
        const pending = [...active.entries()];
        for (const [cancel] of pending) cancel();
        await Promise.all(pending.map(([, done]) => done));
        await start(event, ctx);
    });
    pi.on("session_compact", start);
    pi.on("session_shutdown", async () => {
        closed = true;
        epoch++;
        const pending = [...active.entries()];
        for (const [cancel] of pending) cancel();
        await Promise.all(pending.map(([, done]) => done));
    });
    pi.on("tool_result", async (event, ctx) => {
        const value = await run(event, "tool", ctx);
        if (!value?.line) return;
        return {
            content: [...event.content, { type: "text", text: value.line }],
            details: event.details,
            structuredContent: event.structuredContent,
            isError: event.isError,
            usage: event.usage,
        };
    });
    pi.on("agent_before_settle", async (event, ctx) => {
        if (event.outcome !== "completed" || ctx.signal?.aborted) return;
        const value = await run(event, "stop", ctx);
        if (!value?.line || ctx.signal?.aborted) return;
        return {
            entries: [...event.entries, { type: "custom_message", customType: "locust", content: value.line, display: true }],
            continue: event.continue || value.keep_going,
        };
    });
}
