//! Setup-owned shell entry point. Paths are quoted data; secret bytes are never embedded.
use super::{Failure, Path, SetupSpec};

fn quote(path: &Path) -> Result<String, Failure> {
    let text = path
        .to_str()
        .filter(|text| !text.chars().any(char::is_control))
        .ok_or_else(|| {
            Failure::invalid("launcher paths must be UTF-8 without control characters")
        })?;
    Ok(format!("'{}'", text.replace('\'', "'\\''")))
}

pub(super) fn render(spec: &SetupSpec) -> Result<Vec<u8>, Failure> {
    // Reserve these spellings even after `--`: another option can consume that
    // delimiter as its value. Literal text equal to a reserved flag can use stdin.
    Ok(format!(
        r#"#!/bin/sh
# Generated by locust setup. Reconfigure through setup plan/apply.
for argument do
  case "$argument" in
    --home|--home=*|--credential|--credential=*|--session|--session=*|--owner|--owner=*|--as|--as=*)
      printf '%s\n' 'locust: this launcher has a fixed agent binding; authority and binding overrides are not accepted' >&2
      exit 2 ;;
  esac
done
exec {} --home {} --credential {} --session {} "$@"
"#,
        quote(&spec.executable)?,
        quote(&spec.daemon_home)?,
        quote(&spec.credential)?,
        quote(&spec.session)?,
    )
    .into_bytes())
}

pub(super) fn skill(source: &[u8], launcher: &Path) -> Result<Vec<u8>, Failure> {
    let source = std::str::from_utf8(source)
        .map_err(|_| Failure::invalid("installed skill must be UTF-8"))?;
    // Preserve frontmatter verbatim so clients still discover the same skill.
    let mut lines = source.split_inclusive('\n');
    let first = lines.next().unwrap_or("");
    let insert = if first.trim_end_matches(['\r', '\n']) == "---" {
        let mut end = first.len();
        let mut closed = false;
        for line in lines {
            end += line.len();
            if line.trim_end_matches(['\r', '\n']) == "---" {
                closed = true;
                break;
            }
        }
        if !closed {
            return Err(Failure::invalid("installed skill has unclosed frontmatter"));
        }
        end
    } else {
        0
    };
    let binding = format!(
        "\n# Installed Locust CLI\n\n\
         In every command below, replace the `locust` executable with this exact\n\
         command prefix, including its shell quoting:\n\n\
         ```sh\n{}\n```\n\n\
         The launcher binds the installed executable, daemon home, enrolled agent\n\
         credential and execution session. It needs no PATH or LOCUST environment\n\
         setup. Do not add --home, --credential, --session, --owner or --as, or search\n\
         process environments for credentials. These flag spellings are reserved;\n\
         use standard input when literal note/result text equals one of them.\n\
         Owner actions remain with the local participant. The launcher does not\n\
         grant permissions or bypass the client's approval policy.\n\n",
        quote(launcher)?
    );
    Ok(format!("{}{}{}", &source[..insert], binding, &source[insert..]).into_bytes())
}
